In [1]:
import numpy as np
import pandas as pd

In [3]:
ser = pd.Series(np.random.random(5), name = "Colunn 01")

In [4]:
ser

0    0.139291
1    0.975023
2    0.347769
3    0.756653
4    0.517153
Name: Colunn 01, dtype: float64

In [5]:
ser[2]

0.347768768989112

In [6]:
from pandas_datareader import data as wb

In [7]:
PG = wb.DataReader('PG', data_source='yahoo', start='1995-1-1')

In [8]:
PG

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
1995-01-03,15.625000,15.437500,15.468750,15.593750,3318400.0,8.014159
1995-01-04,15.656250,15.312500,15.531250,15.468750,2218800.0,7.949922
1995-01-05,15.437500,15.218750,15.375000,15.250000,2319600.0,7.837492
1995-01-06,15.406250,15.156250,15.156250,15.281250,3438000.0,7.853555
1995-01-09,15.406250,15.187500,15.343750,15.218750,1795200.0,7.821431
1995-01-10,15.437500,15.187500,15.281250,15.406250,4364000.0,7.917796
1995-01-11,15.593750,15.375000,15.593750,15.375000,3738400.0,7.901737
1995-01-12,15.531250,15.312500,15.375000,15.531250,3307600.0,7.982037
1995-01-13,15.843750,15.531250,15.593750,15.625000,3992800.0,8.075714
1995-01-16,15.968750,15.750000,15.906250,15.750000,3677200.0,8.140323
1995-01-17,15.812500,15.656250,15.718750,15.812500,2437600.0,8.172624
1995-01-18,15.750000,15.437500,15.687500,15.468750,3535200.0,7.994962
1995-01-19,15.406250,15.343750,15.343750,15.406250,2491200.0,7.962657
1995-01-20,15.406250,15.250000,15.406250,15.343750,5130800.0,7.930354
1995-01-23,15.500000,15.187500,15.187500,15.500000,3147200.0,8.011112
1995-01-24,15.531250,15.375000,15.500000,15.468750,2016400.0,7.994962
1995-01-25,15.781250,15.437500,15.500000,15.687500,2802400.0,8.108018
1995-01-26,15.843750,15.687500,15.718750,15.750000,3124000.0,8.140323
1995-01-27,16.250000,15.812500,15.812500,16.187500,6247200.0,8.366442
1995-01-30,16.562500,16.093750,16.125000,16.437500,5226400.0,8.495652
1995-01-31,16.500000,16.281250,16.343750,16.281250,3934800.0,8.414895
1995-02-01,16.343750,15.937500,16.343750,15.968750,3047200.0,8.253387
1995-02-02,16.125000,15.875000,15.968750,16.093750,3810400.0,8.317990
1995-02-03,16.375000,16.187500,16.218750,16.250000,4442800.0,8.398746
1995-02-06,16.625000,16.281250,16.281250,16.625000,4003600.0,8.592562
1995-02-07,16.593750,16.406250,16.562500,16.593750,2380400.0,8.576411
1995-02-08,16.593750,16.406250,16.593750,16.406250,2481200.0,8.479506
1995-02-09,16.468750,16.312500,16.437500,16.375000,2143600.0,8.463348
1995-02-10,16.406250,16.156250,16.343750,16.343750,2445600.0,8.447202
1995-02-13,16.468750,16.312500,16.312500,16.468750,1726400.0,8.511809
...,...,...,...,...,...,...
2021-10-15,144.869995,143.679993,144.520004,144.419998,6923700.0,143.530228
2021-10-18,143.699997,142.100006,143.550003,142.339996,9119000.0,141.463028
2021-10-19,140.820007,138.800003,139.080002,140.660004,9555300.0,139.793396
2021-10-20,141.960007,139.850006,140.149994,141.210007,7352700.0,140.340012
2021-10-21,141.160004,139.179993,140.860001,139.330002,6545500.0,139.330002
2021-10-22,141.009995,139.320007,139.389999,140.830002,5265000.0,140.830002
2021-10-25,140.919998,139.050003,140.410004,140.850006,5382100.0,140.850006
2021-10-26,143.179993,141.240005,141.619995,142.850006,6234900.0,142.850006
2021-10-27,143.679993,141.690002,143.139999,141.830002,9643500.0,141.830002
2021-10-28,142.880005,141.710007,141.889999,142.679993,4538500.0,142.679993
2021-10-29,143.479996,142.020004,142.160004,142.990005,6239500.0,142.990005
2021-11-01,143.800003,142.490005,143.360001,142.639999,5038900.0,142.639999
2021-11-02,144.580002,142.279999,142.720001,144.059998,9954300.0,144.059998
2021-11-03,145.110001,143.520004,144.130005,145.050003,7620100.0,145.050003
2021-11-04,145.389999,142.339996,142.839996,145.320007,6402500.0,145.320007
2021-11-05,146.369995,144.800003,145.440002,146.039993,6062700.0,146.039993
2021-11-08,146.100006,144.020004,145.500000,144.949997,5854400.0,144.949997
2021-11-09,145.830002,144.580002,145.029999,145.389999,4873100.0,145.389999
2021-11-10,147.309998,145.589996,145.740005,146.820007,7334900.0,146.820007
2021-11-11,146.970001,146.210007,146.860001,146.399994,4096300.0,146.399994
2021-11-12,147.080002,145.979996,146.740005,146.559998,5687400.0,146.559998
2021-11-15,147.750000,146.470001,147.029999,147.399994,5510200.0,147.399994
2021-11-16,148.589996,147.009995,147.389999,147.190002,7603900.0,147.190002
2021-11-17,147.779999,146.419998,146.970001,147.100006,4900200.0,147.100006
2021-11-18,148.080002,146.509995,147.039993,147.119995,5509300.0,147.119995
2021-11-19,148.229996,146.789993,147.949997,146.820007,6263700.0,146.820007
2021-11-22,148.940002,146.830002,146.970001,147.800003,6625400.0,147.800003
2021-11-23,149.500000,147.669998,147.830002,149.440002,7912800.0,149.440002
2021-11-24,148.880005,147.679993,148.770004,148.660004,5665200.0,148.660004
2021-11-26,149.720001,147.309998,148.580002,147.470001,6299800.0,147.470001

In [9]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6775 entries, 1995-01-03 to 2021-11-26
Data columns (total 6 columns):
High         6775 non-null float64
Low          6775 non-null float64
Open         6775 non-null float64
Close        6775 non-null float64
Volume       6775 non-null float64
Adj Close    6775 non-null float64
dtypes: float64(6)
memory usage: 370.5 KB

In [11]:
PG.head()

                High       Low      Open     Close     Volume  Adj Close
Date
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   8.014159
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   7.949922
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   7.837492
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   7.853555
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   7.821431

In [12]:
PG.tail()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-11-19,148.229996,146.789993,147.949997,146.820007,6263700.0,146.820007
2021-11-22,148.940002,146.830002,146.970001,147.800003,6625400.0,147.800003
2021-11-23,149.500000,147.669998,147.830002,149.440002,7912800.0,149.440002
2021-11-24,148.880005,147.679993,148.770004,148.660004,5665200.0,148.660004
2021-11-26,149.720001,147.309998,148.580002,147.470001,6299800.0,147.470001

In [15]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source='yahoo', start='1995-1-1')['Adj Close']

In [16]:
new_data.tail()

                    PG        MSFT          T          F          GE
Date
2021-11-19  146.820007  343.109985  24.129999  19.389999   99.959999
2021-11-22  147.800003  339.829987  24.700001  20.480000  101.040001
2021-11-23  149.440002  337.679993  24.760000  20.200001  102.080002
2021-11-24  148.660004  337.910004  24.469999  20.250000  102.230003
2021-11-26  147.470001  329.679993  24.219999  19.750000   97.839996